// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "MentalHealthCare/models"

	mock "github.com/stretchr/testify/mock"
)

type AdminRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: adminReq
func (_m *AdminRepository) GetByEmail(loginReq models.LoginRequest) (models.Admin, error) {
	ret := _m.Called(loginReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(models.LoginRequest) (models.Admin, error)); ok {
		return rf(loginReq)
	}
	if rf, ok := ret.Get(0).(func(models.LoginRequest) models.Admin); ok {
		r0 = rf(loginReq)
	} else {
		r0 = ret.Get(0).(models.Admin)
	}

	if rf, ok := ret.Get(1).(func(models.LoginRequest) error); ok {
		r1 = rf(loginReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: adminReq
func (_m *AdminRepository) Create(adminReq models.AdminRequest) (models.Admin, error) {
	ret := _m.Called(adminReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(models.AdminRequest) (models.Admin, error)); ok {
		return rf(adminReq)
	}
	if rf, ok := ret.Get(0).(func(models.AdminRequest) models.Admin); ok {
		r0 = rf(adminReq)
	} else {
		r0 = ret.Get(0).(models.Admin)
	}

	if rf, ok := ret.Get(1).(func(models.AdminRequest) error); ok {
		r1 = rf(adminReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *AdminRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *AdminRepository) GetAll() ([]models.Admin, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Admin, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Admin); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *AdminRepository) GetByID(id string) (models.Admin, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Admin, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Admin); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Admin)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: adminReq, id
func (_m *AdminRepository) Update(adminReq models.AdminRequest, id string) (models.Admin, error) {
	ret := _m.Called(adminReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(models.AdminRequest, string) (models.Admin, error)); ok {
		return rf(adminReq, id)
	}
	if rf, ok := ret.Get(0).(func(models.AdminRequest, string) models.Admin); ok {
		r0 = rf(adminReq, id)
	} else {
		r0 = ret.Get(0).(models.Admin)
	}

	if rf, ok := ret.Get(1).(func(models.AdminRequest, string) error); ok {
		r1 = rf(adminReq, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAdminRepository creates a new instance of AdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminRepository {
	mock := &AdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}