// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "MentalHealthCare/models"

	mock "github.com/stretchr/testify/mock"
)

// DoctorRepository is an autogenerated mock type for the DoctorRepository type
type DoctorRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: doctorReq
func (_m *DoctorRepository) Create(doctorReq models.Doctor) (models.Doctor, error) {
	ret := _m.Called(doctorReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Doctor
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Doctor) (models.Doctor, error)); ok {
		return rf(doctorReq)
	}
	if rf, ok := ret.Get(0).(func(models.Doctor) models.Doctor); ok {
		r0 = rf(doctorReq)
	} else {
		r0 = ret.Get(0).(models.Doctor)
	}

	if rf, ok := ret.Get(1).(func(models.Doctor) error); ok {
		r1 = rf(doctorReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *DoctorRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *DoctorRepository) GetAll() ([]models.Doctor, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Doctor
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Doctor, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Doctor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Doctor)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *DoctorRepository) GetByID(id string) (models.Doctor, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Doctor
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Doctor, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Doctor); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Doctor)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: doctorReq, id
func (_m *DoctorRepository) Update(doctorReq models.Doctor, id string) (models.Doctor, error) {
	ret := _m.Called(doctorReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Doctor
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Doctor, string) (models.Doctor, error)); ok {
		return rf(doctorReq, id)
	}
	if rf, ok := ret.Get(0).(func(models.Doctor, string) models.Doctor); ok {
		r0 = rf(doctorReq, id)
	} else {
		r0 = ret.Get(0).(models.Doctor)
	}

	if rf, ok := ret.Get(1).(func(models.Doctor, string) error); ok {
		r1 = rf(doctorReq, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDoctorRepository creates a new instance of DoctorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDoctorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DoctorRepository {
	mock := &DoctorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
