// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "MentalHealthCare/models"

	mock "github.com/stretchr/testify/mock"
)

// InformationRepository is an autogenerated mock type for the InformationRepository type
type InformationRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: infoReq
func (_m *InformationRepository) Create(infoReq models.Information) (models.Information, error) {
	ret := _m.Called(infoReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Information
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Information) (models.Information, error)); ok {
		return rf(infoReq)
	}
	if rf, ok := ret.Get(0).(func(models.Information) models.Information); ok {
		r0 = rf(infoReq)
	} else {
		r0 = ret.Get(0).(models.Information)
	}

	if rf, ok := ret.Get(1).(func(models.Information) error); ok {
		r1 = rf(infoReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *InformationRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *InformationRepository) GetAll() ([]models.Information, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Information
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Information, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Information); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Information)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *InformationRepository) GetByID(id string) (models.Information, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Information
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Information, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Information); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Information)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: infoReq, id
func (_m *InformationRepository) Update(infoReq models.Information, id string) (models.Information, error) {
	ret := _m.Called(infoReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Information
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Information, string) (models.Information, error)); ok {
		return rf(infoReq, id)
	}
	if rf, ok := ret.Get(0).(func(models.Information, string) models.Information); ok {
		r0 = rf(infoReq, id)
	} else {
		r0 = ret.Get(0).(models.Information)
	}

	if rf, ok := ret.Get(1).(func(models.Information, string) error); ok {
		r1 = rf(infoReq, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInformationRepository creates a new instance of InformationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInformationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InformationRepository {
	mock := &InformationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
